### ISSUE TITLE
Support the currency semantic type for all currency fields

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#15]
When adding an extra charge or currency field in the schema add the currency type to the meta data on the schema. The currently set currency is available in the [/accounts endpoint](https://app.swaggerhub.com/apis-docs/WildApricot/wild-apricot_public_api/7.7.0#/Accounts/GetAccountsList) in this structure:

 ```
"Currency": {
      "Code": "string",
      "Name": "string",
      "Symbol": "string"
    }
```

The values are encoded as followed and could be mapped to equivalent [currency semantic type in GDS](https://developers.google.com/datastudio/connector/reference#currency_semantic_types)

```
Code | stringCurrency code according to [ISO4217](https://en.wikipedia.org/wiki/ISO_4217#Active_codes)
Name | stringHuman-readable currency name
Symbol | stringCurrency symbol like $ or €
```

**Comment by miasmos** [comment]
Made api token global so it's only fetched once. Currency `semanticType` in any schema now dynamically matches the currency code on the user's account.

**Comment by asirota** [comment]
@stephenpoole are currently hard-coded CURRENCY_CAD in objects like `Contact` now dynamically switched to the right currency type? There are several that have been hard coded and should be altered to the right system currency type. Example:
` {
      name: "Balance",
      label: "Balance",
      dataType: "NUMBER",
      semantics: {
        conceptType: "DIMENSION",
        semanticGroup: "CURRENCY",
        semanticType: "CURRENCY_CAD"
      }`

**Comment by miasmos** [comment]
Even though they exist in schema, they're replaced at runtime. Could probably just remove them if it's confusing.

**Comment by asirota** [comment]
@stephenpoole that's ok -- it's not a problem.
