### ISSUE TITLE
Use Account ID and User ID as consistent field name

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#19]
Need to add `Account ID` and `User ID` to the contact custom fields. This will allow to blend data with the regular contacts end point effectively removing the need for combining the contacts and contacts (custom fields) together. Note that Auditlog and Invoice also have `Contact ID` as the field name which should be changed to `User ID` as well to be consistent.

**Comment by edtsoi430** [comment]
resolved.
