### ISSUE TITLE
Support GDS date filter to contacts end point date values

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#21]
The Contacts endpoint has various date values that are currently not "filterable" by the [GDS date filter control](https://support.google.com/datastudio/answer/6291067). Lastlogindate is one such field but there are others. Need to add support for using the date filter on Contacts. The Invoices end point does support the date filter for invoice created date, so that functionality can be adapted there.

In general all date fields should be filtered by the built in GDS date control.

[Details on setting the correct configuration parameters in the connector code.](https://developers.google.com/datastudio/connector/date-range)

**Comment by miasmos** [comment]
Added date range control to contacts.
