### ISSUE TITLE
Add a configuration parameter for contacts & custom fields to eliminate archived records/include  members only

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#27]
Add a checkbox to include archived records during the data source configuration for Contacts & Contact custom fields. This is set in `isArchived` boolean field and can be filtered with [$filter in the API call.](https://gethelp.wildapricot.com/en/articles/502#filtering)

Only for Contacts and Contacts custom fields endpoints
Name of checkbox: **Include Archived contacts**
Default value: **off**

**Comment by asirota** [comment]
Also provide a checkbox to include members only. This can be evaluated by checking `Member = true` using $filter

Only for Contacts and Contacts custom fields endpoints
Name of checkbox: **Include Members only**
Default value: **on**

**Comment by asirota** [comment]
Both of these checkboxes should only appear when Contacts or Contacts custom fields endpoint is selected.

**Comment by asirota** [comment]
Looks like it is impossible to set a default value in the code.

**Comment by asirota** [comment]
These don't seem to be being set correctly for the `Contact custom field` object. They are being ignored.

**Comment by miasmos** [comment]
Implementation differs from the above per our discussion:
Include archived contacts should include them when checked and otherwise exclude them.

**Comment by asirota** [comment]
That's correct @stephenpoole - you have the right implementation now, include archive records with the regular records if the `Include Archived contacts` checkbox is checked, otherwise exclude archived records, which is the default state
