### ISSUE TITLE
/Invoices - event ID throwing an error

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#37]
When loading `Event Id` in /Invoices an error is thrown

![image](https://user-images.githubusercontent.com/458134/75902495-14382b80-5e0e-11ea-9507-89b653f9a305.png)

**Comment by miasmos** [comment]
Some voided invoices didn't have the expected `EventRegistration` object. Now checking if it exists, and if not, skipping population of `EventId`.
