### ISSUE TITLE
Make the several field names consistent in all applicable endpoints

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#38]
The `User ID` field is not always properly named, which could make blending more confusing for users.

In `Contacts`

`Member Id` should be `User ID`

In `Account`

`Account number` should be `Account ID`

In `Audit log`

The current `User ID` field should be renamed `Account ID` as it is returning the data for the account ID

`Contact ID` field should be renamed `User ID`

In `Invoice`

the current `User ID` field should be renamed `Account ID` and load the Account ID as it is currently loading `null`

The `Contact ID` field should be renamed `User ID`

**Comment by miasmos** [comment]
Renamed the above fields. Fixed `Account ID` being null.
