### ISSUE TITLE
support Payments endpoint

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#4]
Add support for the [Payments ](https://help.wildapricot.com/display/DOC/Payments+API+V2+call)Wild Apricot endpoint

**Comment by asirota** [comment]
The /Payments object has several pieces of information required for analysis of payments & refunds.

Here are the elements to retrieve and the dimension names to apply following the ->

Id -> `Payment ID` (number)
Value -> `Payment Amount` (currency)
RefundedAmount -> `Refunded Amount` (currency)
Contact.Id -> `User ID` (number)
Contact.Name -> `Contact Name` (string)
CreatedDate -> `Payment Created Date` (date)
UpdatedDate -> `Payment Updated Date` (date)
Tender.Name -> `Tender` (string)
Comment -> `Internal Comment` (string)
PublicComment -> `Public Comment` (string)
AllocatedValue -> `Allocated Value` (currency)
Type -> `Payment Type` (string)
DonationId -> `Donation ID` (number)



```
{
  "PaymentIdentifiers": [
    0
  ],
  "Payments": [
    {
      "Id": 0,
      "Url": "string",
      "Value": 0,
      "DocumentDate": "2020-03-16",
      "Contact": {
        "Id": 0,
        "Url": "string",
        "Name": "string"
      },
      "CreatedDate": "2020-03-16",
      "CreatedBy": {
        "Id": 0,
        "Url": "string"
      },
      "UpdatedDate": "2020-03-16",
      "UpdatedBy": {
        "Id": 0,
        "Url": "string"
      },
      "Tender": {
        "Id": 0,
        "Url": "string",
        "Name": "string"
      },
      "Comment": "string",
      "PublicComment": "string",
      "AllocatedValue": 0,
      "RefundedAmount": 0,
      "Type": "Unknown",
      "DonationId": 0,
      "FieldValues": [
        {
          "FieldName": "string",
          "SystemCode": "string",
          "Value": {}
        }
      ]
    }
  ]
}```

**Comment by asirota** [comment]
Note paging is supported  in this endpoint, there are filters too but they are specific filters rather than a filter string so can leave filters off this endpoint

**Comment by miasmos** [comment]
Added support for payments endpoint.
