### ISSUE TITLE
Total Amount in /Invoice in hard coded currency

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#53]
Looking at the `Total Amount` field in /Invoice it looks like it is being hard coded to CAD$

**Comment by miasmos** [comment]
Fixed the `semanticType` not being set after the first found currency.

**Comment by asirota** [comment]
@stephenpoole The Total Amount in /Invoices is still hard coded to load the CAD amount. I changed the Currency on the sandbox site and the paid amount field updated fine, but the Total Amount field was kept in CAD$  (
![image](https://user-images.githubusercontent.com/458134/77348086-3a673200-6d0f-11ea-9ee0-9fc9a41574a8.png)

**Comment by asirota** [comment]
Confirmed on new data source Total Donated is respecting currency semantic
