### ISSUE TITLE
In /Payments endpoint several dollar amounts not respecting currency type

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#56]
Similar to #53 in the new Payments object several values are not respecting the active currency type (USD on the sandbox site):

`Allocated Value`
`Refunded Amount`

Interesting to note `Payment Amount` is properly in USD.

**Comment by miasmos** [comment]
Not able to reproduce on 2.0. Note that #4 was deployed to uat, which did not include changes for #53. I've deployed 2.0 to uat.

**Comment by asirota** [comment]
Thank you, I see it's updating the semantic correctly now.
