### ISSUE TITLE
In /Contacts Total Donated not respecting the currency semantic

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#57]
In Contacts object the `Total Donated` field is not respecting the current currency semantic

**Comment by miasmos** [comment]
Not able to reproduce on 2.0. Note that #4 was deployed to uat, which did not include changes for #53. I've deployed 2.0 to uat.

**Comment by asirota** [comment]
confirmed on a new data source currency semantic is being respected on Total Donated
