### ISSUE TITLE
Add support for sent email endpoint

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#6]
Support email [marketing statistics and emails sent ](https://gethelp.wildapricot.com/en/articles/1606-sentemails-admin-api-call)end point

**Comment by miasmos** [comment]
Added support for /sentemails endpoint with paging. Added every field except `Origin`, `Body`, and `SubOriginId`. `Origin`/`SubOriginId` because it doesn't seem useful and `Body` because of privacy concerns. Let me know if those aren't valid assumptions.

**Comment by asirota** [comment]
Looks great @stephenpoole - 
`"SendingType": "Automatic"` would be useful to filter between automatic and manual emails.

**Comment by miasmos** [comment]
Added `SendingType`
