### ISSUE TITLE
Date issues with our current date semantic

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#62]
For now I am testing this in `Invoices` to show the issues I am having. I am using this link

https://datastudio.google.com/s/taqiAtScODE

(page 5).
The `invoice created date` should be a normal data type that you can reformat using the built in date formatting features. Unfortunately this does not work so we have to resort to todate functions to get the date to format the way we want. This is very important for grouping by month to do aggregations on invoices for example.

Setting the granularity should convert to a different level of date granularity but we get `null`s instead.
![2020-04-01_9-08-36](https://user-images.githubusercontent.com/458134/78140797-90676400-73f8-11ea-824e-22ee23cad539.png)

I have to resort to using `todate()` to grab the necessary date components and reformatting them in various means.

![2020-04-01_9-10-39](https://user-images.githubusercontent.com/458134/78141400-711d0680-73f9-11ea-937a-e0a4cb901bbe.png)

or this to concatenate month and day

![2020-04-01_9-12-52](https://user-images.githubusercontent.com/458134/78141417-77ab7e00-73f9-11ea-80ff-c7eb774631f8.png)

This is not ideal nor user-friendly. It appears the underlying data format from WA is either nonstandard or we are not setting the date semantic/format correctly to let GDS treat our date properly.

**Comment by asirota** [comment]
The workaround for now is to use the `TODATE()` function to cast into the correct format you want for 
![2020-04-01_15-42-55](https://user-images.githubusercontent.com/458134/78179834-da1f7100-742f-11ea-8ae3-d12e75d7001f.png)
the date:

**Comment by miasmos** [comment]
The dates were never being properly parsed, so in the reports they were just strings, not dates.

**Comment by asirota** [comment]
Ok here are the fields that are still not properly working with setting type/granularity
`Contacts`
- `Level last changed`
- `Member since`
- `Renewal due`

**Comment by asirota** [comment]
Merged into 2.1 release
