### ISSUE TITLE
Support custom fields for Contacts endpoint

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#7]
add support for custom fields to be added as dimensions to the current Members endpoint.

The connector should have a configuration checkbox to “Include custom fields” to the fixed schema when Members is selected. The default behaviour is on. 

This may make it easier for people to just want to analyze the fixed schema fields or include the custom fields they have configured and the fixed schema fields together.

**Comment by asirota** [comment]
The current test environment for custom fields does not handle date fields correctly (eg Birthday)

**Comment by asirota** [comment]
(Resolved) Make sure the Contacts custom field functionality includes UserID and AccountID as implemented in the Contacts endpoint. Right now it is impossible to identify the primary key for these records.

**Comment by asirota** [comment]
If possible can the custom fields in the schema be ordered alphabetically so it is easy to find them?

**Comment by asirota** [comment]
(Resolved) In the configuration of the end points on WARM please place Contacts first and then Contacts (custom fields) right underneath them so they are together in the drop down.

**Comment by asirota** [comment]
There is always one extra null record being returned for the Contacts (custom fields) end point. It is always the last record.

**Comment by asirota** [comment]
Date data type fields are not being returned in the custom fields. The schema should assign a DATE datatype to these fields.

**Comment by asirota** [comment]
Radio button with extra charge field not returning data, and should return a string value (not numeric as it does now) @stephenpoole can you look at this one to make sure this is working as intended, a radio button extra charge field called `Membership Fee Based on Salary` is setup in the sandbox on contacts

**Comment by edtsoi430** [comment]
> In the configuration of the end points on WARM please place Contacts first and then Contacts (custom fields) right underneath them so they are together in the drop down.

Resolved

**Comment by edtsoi430** [comment]
> The current test environment for custom fields does not handle date fields correctly (eg Birthday)

resolved

**Comment by asirota** [comment]
(Resolved) Please make the semantic type for User ID and Account ID to a number, not a string as it is now.

**Comment by edtsoi430** [comment]
> Please make the semantic type for User ID and Account ID to a number, not a string as it is now.

resolved.

**Comment by asirota** [comment]
I'll reopen until this one until we ship v2.

**Comment by asirota** [comment]
@stephenpoole can you fix the issue with extra charge calculation fields. They currently load as `null`

Sample field on sandbox is called Beach Pass and is filled in for user 37415038. This is a numeric field that contains the number stored in  the extra charge calculation.
