### ISSUE TITLE
Contact custom fields not respecting the include archived contact and include members only

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#71]
I am testing the config flags for 
`include archived contact` and `include members only` and note that in the `Contact custom fields` object neither flag has any effect.

This works fine for the `Contacts` object though so, not sure if these config parameters are properly being passed to the API call.

**Comment by miasmos** [comment]
You are right, the filter param wasn't being passed to the api call

**Comment by asirota** [comment]
It doesn't look like the `Return count only` config parameter or the `Count` schema element is included in this object either.

**Comment by asirota** [comment]
Also the $filter parameter is not being passed and throws an error and a filter is added into the configuration parameter on the data source

**Comment by miasmos** [comment]
Fixed count not being included in the custom schema and the custom filter not being used.

**Comment by asirota** [comment]
Looking good -- one curious issue I found. Why do these filters return an error?

`'User ID' gt 1`

`'User ID' ne NULL`

`'User ID' eq NULL`

Only the `eq` filter seems to work.

**Comment by miasmos** [comment]
Looks like the api doesn't support querying `User ID` in that way.
`Operator NotNull is not supported for attribute User ID`
`Operator Null is not supported for attribute User ID`

**Comment by asirota** [comment]
Ok that's fine.
