### ISSUE TITLE
Introduce a DEV/UAT/PROD label that can be added dynamically into the code

### ISSUE THREAD

**Issue by asirota** [asirota/gds-wildapricot-connector#79]
When we deploy code to DEV/UAT/PROD currently we need to introduce this string in 3 places:

In appscript.json (description and shortdescription) as well as line 1887 on wa_connector.gs to identify the User-Agent

Can we make this easier to change in one place and have it cascade down to the various places it needs to be used?

**Comment by miasmos** [comment]
This would require the introduction of deploy automation through something like [Travis CI](https://travis-ci.com/). I can certainly do it, but if it's solely for the above reason I'm not sure it's worth the time investment.

**Comment by asirota** [comment]
I suppose it can't be a variable we change in the code and rather needs some post processing to make it work. No it's not worth the time to implement CI for this simple change. I can remember where to change it if necessary.
